import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../core/session/app_session.dart';
import '../../clients/data/clients_repository.dart';

class CreditsPage extends StatefulWidget{const CreditsPage({super.key});@override State<CreditsPage> createState()=>_CreditsPageState();}
class _CreditsPageState extends State<CreditsPage>{final db=Supabase.instance.client;late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=_list();}Future<List<Map<String,dynamic>>> _list()async{final id=await AppSession().businessId();final x=await db.from('credits').select('*,clients(full_name,phone,whatsapp)').eq('business_id',id).neq('status','paid').neq('status','cancelled').order('due_date');return List<Map<String,dynamic>>.from(x);}void refresh()=>setState(()=>future=_list());String _normalise(String v){var n=v.replaceAll(RegExp(r'[^0-9+]'),'');if(n.startsWith('00'))n=n.substring(2);if(n.startsWith('0'))n='226${n.substring(1)}';if(n.startsWith('+'))n=n.substring(1);return n;}Future<void> pay(Map<String,dynamic> x)async{final remaining=(x['original_amount'] as num).toDouble()-(x['paid_amount'] as num).toDouble();final ctrl=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Enregistrer un paiement'),content:TextField(controller:ctrl,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'Montant restant : ${remaining.toStringAsFixed(0)} F')),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Annuler')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Enregistrer'))]));if(ok==true){try{await ClientsRepository().payCredit(creditId:x['id'],amount:double.parse(ctrl.text.replaceAll(' ', '').replaceAll(',','.')),clientId:x['client_id']);refresh();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Impossible : $e')));}}ctrl.dispose();}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Crédits à recouvrer'),actions:[IconButton(onPressed:refresh,icon:const Icon(Icons.refresh))]),body:FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final list=s.data!;if(list.isEmpty)return const Center(child:Text('Aucun crédit en cours.'));return ListView.separated(padding:const EdgeInsets.all(16),itemCount:list.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i){final x=list[i];final cl=x['clients'] as Map?;final phone=(cl?['phone']??cl?['whatsapp']??'').toString();final rest=(x['original_amount'] as num).toDouble()-(x['paid_amount'] as num).toDouble();return Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(cl?['full_name']?.toString()??'Client',style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16))),Text('${rest.toStringAsFixed(0)} F',style:TextStyle(fontWeight:FontWeight.w800,color:Theme.of(c).colorScheme.primary))]),const SizedBox(height:5),Text('Échéance : ${x['due_date']??'Non définie'}'),Text('Crédit : ${x['original_amount']} F • payé : ${x['paid_amount']} F'),const SizedBox(height:10),Wrap(spacing:8,children:[if(phone.isNotEmpty)OutlinedButton.icon(onPressed:()=>launchUrl(Uri.parse('tel:$phone')),icon:const Icon(Icons.call),label:const Text('Appeler')),if(phone.isNotEmpty)OutlinedButton.icon(onPressed:()=>launchUrl(Uri.parse('https://wa.me/${_normalise(phone)}'),mode:LaunchMode.externalApplication),icon:const Icon(Icons.chat),label:const Text('Relancer WhatsApp')),FilledButton.icon(onPressed:()=>pay(x),icon:const Icon(Icons.payments_outlined),label:const Text('Paiement'))])])));});}));}
