import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../core/brand/apnbf_logo.dart';
import '../data/auth_repository.dart';

class AuthPage extends StatefulWidget { const AuthPage({super.key}); @override State<AuthPage> createState()=>_AuthPageState(); }
class _AuthPageState extends State<AuthPage>{
  final _formKey=GlobalKey<FormState>(); final _name=TextEditingController(); final _email=TextEditingController(); final _password=TextEditingController(); final _phone=TextEditingController(); final _repository=AuthRepository(); bool _isLogin=true,_loading=false,_obscure=true; String? _error;
  @override void dispose(){_name.dispose();_email.dispose();_password.dispose();_phone.dispose();super.dispose();}
  Future<void> _submit()async{if(!_formKey.currentState!.validate())return;setState((){_loading=true;_error=null;});try{if(_isLogin){await _repository.signIn(email:_email.text.trim(),password:_password.text);if(!mounted)return;context.go('/dashboard');}else{await _repository.signUp(fullName:_name.text.trim(),email:_email.text.trim(),password:_password.text,phone:_phone.text.trim());if(!mounted)return;context.go('/onboarding');}}on AuthException catch(e){if(mounted)setState(()=>_error=e.message);}on PostgrestException catch(e){if(mounted)setState(()=>_error=e.message);}catch(_){if(mounted)setState(()=>_error='Une erreur est survenue. Vérifie tes informations et réessaie.');}finally{if(mounted)setState(()=>_loading=false);}}
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:480),child:Column(children:[const ApnbfLogo(height:64),const SizedBox(height:24),Text(_isLogin?'Bon retour.':'Crée ton espace APNBF.'),const SizedBox(height:8),Text(_isLogin?'Retrouve ton activité et tes clients.':'Une gestion simple, pensée pour ton activité.',textAlign:TextAlign.center),const SizedBox(height:24),Card(child:Padding(padding:const EdgeInsets.all(20),child:Form(key:_formKey,child:Column(children:[if(!_isLogin)...[TextFormField(controller:_name,textCapitalization:TextCapitalization.words,decoration:const InputDecoration(labelText:'Nom complet'),validator:(v)=>v==null||v.trim().isEmpty?'Nom requis':null),const SizedBox(height:12),TextFormField(controller:_phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Téléphone'),validator:(v)=>v==null||v.trim().isEmpty?'Téléphone requis':null),const SizedBox(height:12)],TextFormField(controller:_email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'E-mail'),validator:(v)=>v==null||!v.contains('@')?'E-mail invalide':null),const SizedBox(height:12),TextFormField(controller:_password,obscureText:_obscure,decoration:InputDecoration(labelText:'Mot de passe',suffixIcon:IconButton(onPressed:()=>setState(()=>_obscure=!_obscure),icon:Icon(_obscure?Icons.visibility_outlined:Icons.visibility_off_outlined))),validator:(v)=>v==null||v.length<6?'6 caractères minimum':null),if(_error!=null)...[const SizedBox(height:14),Align(alignment:Alignment.centerLeft,child:Text(_error!,style:TextStyle(color:Theme.of(context).colorScheme.error)))],const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:_loading?null:_submit,child:_loading?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):Text(_isLogin?'Se connecter':'Créer mon compte'))),const SizedBox(height:8),TextButton(onPressed:_loading?null:()=>setState((){_isLogin=!_isLogin;_error=null;}),child:Text(_isLogin?'Créer un compte':'J’ai déjà un compte'))])))),]))))));
}
